### ISSUE TITLE
Contribute zh-CN localization to the DevExtreme repo

### ISSUE THREAD

**Issue by BingoRUS** [beginor/dx-locale-zh-cn#2]
Hi,

Would you mind to contribute zh-CN localization to the DevExtreme repository? It will help other developers to get it out of the box.
The DevExtreme repo is [here](https://github.com/DevExpress/DevExtreme), all localization messages are [here](https://github.com/DevExpress/DevExtreme/tree/17_2/js/localization/messages), the Contribution Guide can be found [here](https://github.com/DevExpress/DevExtreme/blob/17_2/CONTRIBUTING.md).

Thanks!

**Comment by beginor** [comment]
OK, I will try it!

**Comment by BingoRUS** [comment]
Thank you!
